spring:
  datasource: { url: jdbc:postgresql://localhost:5432/postgres,
                username: postgres,
                password: entiqe#1998,
                driver-class-name: org.postgresql.Driver }

#  jpa:
#    hibernate:
#    ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
